name: Update sub-web

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'sub-web source repo'
        required: true
        default: 'CareyWang/sub-web'

concurrency: 
  group: sub-web
  # 自动取消其他运行中的workflow
  cancel-in-progress: true 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout toolchain repo
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repo }}
        path: sub-web

    - name: Update sub-web
      run: |
        git clone https://github.com/live2364li/sub.git
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Get dependencies and build
      working-directory: sub-web
      run: |
        yarn install
        yarn build
        
    - name: Clean up
      run: |
        sudo rm -rf files/dist
        sudo cp -rf sub-web/dist files/
        sudo rm -rf sub-web
        
    - name: Add & Commit
      uses: EndBug/add-and-commit@v6
      with:
        author_name: GitHub Action
        author_email: noreply@github.com
        message: "Update sub-web"
        add: "-A"
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
